FROM nginx:latest

# Copy custom nginx.conf to the container's nginx configuration directory
COPY nginx.conf /etc/nginx/nginx.conf

# Copy index.php to the container's default HTML directory
COPY index.php /usr/share/nginx/html/index.php
